### ISSUE TITLE
Experience Buttons Wrong Color in Dark Mode on Safari

### ISSUE THREAD

**Issue by mattlathrop** [gurusabarish/hugo-profile#70] opened 2022-08-31 22:32 UTC
**Describe the bug**
The buttons for switching between various experiences are the wrong color (white with unreadable light grey text) in dark mode on safari 15.5. Chrome seems fine.

**To Reproduce**
1. Go to https://hugo-profile.netlify.app/#experience in safari on a Mac
2. Ensure you are in dark mode
3. Look at buttons for switching to various experiences (i.e. Facebook, Amazon, etc)

**Expected behavior**
Buttons should have a dark background, be readable, and be styled as in chrome
**Screenshots**
[Screenshot](https://ibb.co/kyCb78p)

**Desktop (please complete the following information):**
 - OS: MacOS 12.4
 - Browser Safari
 - Version 15.5

**Additional context**

**Comment by AndreaPaolo** [comment] 2022-09-01 18:21
#### Message translated with google transalte
Hi, I also have the same problem. The problem is the property of the button "-webkit-appearance". Disabling this property looks the same as google chrome.
#### Screenshots
[problem](https://ibb.co/SKkGQCt)
[possible solution](https://ibb.co/y0pj1nF)

#### Original language
Ciao, anche io ho lo stesso problema. Il problema è la proprietà del pulsante "-webkit-appearance". La disabilitazione di questa proprietà ha lo stesso aspetto di Google Chrome.

#### Desktop
- OS: MacOS 12.4
- Browser: Safari 
- Version: 15.5(17613.2.7.1.8)
- Comparison browser: Google Chrome 
- Version: 104.0.5112.79

**Comment by gurusabarish** [comment] 2022-09-02 16:23
Fixed in #72

**Closed by gurusabarish** 2022-09-02 16:23 UTC
